spring:
  datasource:
    url: jdbc:mysql://localhost:3306/discografia?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: 123456
    
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
    open-in.view: false